public enum ActionType
{
    UNIVERSAL_ATTACK,
    UNIVERSAL_MOVE,
    UNIVERSAL_TAKE_DAMAGE,
    UNIVERSAL_DEATH,
    KNIGHT_BOMB_ABILITY,
    INVALID_INCREASE,
    INVALID_DIE,
    TURTLE_HIGHLIGHT,
    COMBAT_START,
    UNIVERSAL_FIGURE_SPAWN,
    NEEDLE_HIGHLIGHT
}